### ISSUE TITLE
feature/ Add a status column to the games table in the database

### ISSUE THREAD

**Issue by Scotthorn0** [AlaMurkan-FIFA-Boyz-2017-Dremz2Lyf/Game-Manager#43]
Adding a status column with a string of "created", "active", or "disabled" lets us change the class on the rendered element, highlight the current game, and grey out played games.

This should also make @Chrisqtran3's job easier in theory, because it should enable him to check scores and update info only for games already finished

I picture it like this:
`
<li className="list-group-item " + {props.status} onClick={function(){ props.click(props.gameIndex) }}>
`

Using the "created", "active", "disabled" naming convention above it will just add the string to the class and will highlight as we want.

**Comment by wise-na** [comment]
Believe this is all completed.
